CREATE TABLE IF NOT EXISTS companies(
    transactionID INTEGER PRIMARY KEY,
    gvkey INTEGER,
    companyName VARCHAR,
    companyISIN VARCHAR,
    companySEDOL VARCHAR,
    insiderID INTEGER,
    insiderName VARCHAR,
    insiderRelation VARCHAR,
    insiderLevel CHAR,
    connectionType VARCHAR,
    connectedInsiderName VARCHAR,
    connectedInsiderPosition VARCHAR,
    transactionType VARCHAR,
    transactionLabel VARCHAR,
    iid VARCHAR,
    securityISIN VARCHAR,
    securitySEDOL VARCHAR,
    securityDisplay VARCHAR,
    assetClass VARCHAR,
    shares BIGINT,
    inputdate INTEGER,
    tradedate INTEGER,
    maxTradedate INTEGER,
    price FLOAT,
    maxPrice FLOAT,
    value FLOAT,
    currency VARCHAR(3),
    valueEUR FLOAT,
    unit VARCHAR(3),
    correctedTransactionID INTEGER,
    source VARCHAR,
    tradeSignificance INTEGER,
    holdings BIGINT,
    filingURL VARCHAR,
    exchange VARCHAR
);
